# Change these first
owner: WithdewHua # Your GitHub username
repo: web-status # Your Github repository name

# Add your sites here
sites:
  - name: 方寸间
    url: https://10101.io
  - name: Subconverter | 方寸间
    url: https://web.api.10101.io
  - name: 储物间 | 方寸间
    url: https://asset.10101.io
  - name: AdguardHome | 方寸间
    url: https://dns.10101.io
  - name: Self-Hosted Bitwarden | 方寸间
    url: https://vault.10101.io

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.10101.io
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://10101.io/favicon.ico
  name: 问平安 | 方寸间
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Blog
      href: https://10101.io

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
